. "$HOME/.cargo/env"
#export WALLPAPER_DEFAULT="peakpx(2).jpg"
export WALLPAPER="$HOME/Wallpapers/test/mari-k-final-hirez.jpg"
###export WALLPAPER_DEFAULT="saturn-rings-wide.png"
###export WALLPAPER_DEFAULT="meet-me-at-sunset-wallpaper.jpg"
export PRIMARY="#cc7acc"
#export WALLPAPER_DEFAULT="pastel-window_blured.png"
#export WALLPAPER_DEFAULT="wallpaperflare.com_wallpaper(3).jpg"
#export WALLPAPER_DEFAULT="bici.jpg"
export SERV="$HOME/IdeaProjects/_servers/magic-vanilla-dev/server/"
export PATH="$HOME/.scripts/direct:$PATH"
export MED="$HOME/Documents/Notes/Médecine"
export MSRC="$MED/_Sources/PDF"
export BUILD_DIR="/usr/share/builds"

export EDITOR="/usr/bin/hx"
export TERMINAL="/usr/bin/wezterm"
export TERMINAL_BACKUP="/usr/bin/alacritty"
