# Documentation about configuration:
# https://docs.helix-editor.com/configuration.html

theme = "onedark_alpha"

[editor]
line-number = "relative"
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
