blur:
{
	method = "dual_kawase";
	strength = 4
}

blur-background-exclude = [
	  # prevents picom from blurring the background
	  "role  = 'xborder'",
	  "class_g  = 'Rofi'",
	  "class_g = 'jetbrains-idea-ce'",

];


rounded-corners-exclude = [ "class_g = 'Rofi'" ];

#opacity-rule = [
#  "100:class_g = 'Alacritty' && focused",
#  "60:class_g = 'Alacritty' && !focused"
#];

backend = "glx";
corner-radius = 12; 
round-borders = 12;
shadow = false;
vsync = true;
