# https://yazi-rs.github.io/docs/configuration/theme

[filetype]
rules = [
  { name = "*/", fg = "lightyellow" }
]

[icon]
prepend_rules = [
  { name = "*/", text = "󰉋" },
  { name = "*.png", text = "󰺰" },
  { name = "*.jpg", text = "󰈟" },
  { name = "*.jpeg", text = "󰈟" },
  { name = "*.webp", text = "󰈟" },
  { name = "*.svg", text = "󰕣" },
  { name = "*.bmp", text = "󰈟" },
  { name = "*.gif", text = "󱀺" },
  { name = "*.raw", text = "󱨏" },
  { name = "*.mp4", text = "󰈫" },
  { name = "*.avi", text = "󰈫" },
  { name = "*.mpeg-4", text = "󰈫" },
  { name = "*.mkv", text = "󰈫" },
  { name = "*.mov", text = "󰈫" },
  { name = "*.webm", text = "󰈫" },
  { name = "*.flv", text = "󰈫" },
  { name = "*.mp3", text = "󰈣" },
  { name = "*.ogg", text = "󰈣" },
  { name = "*.wav", text = "󰈣" },
  { name = "*.m4a", text = "󰈣" },
  { name = "*.flac", text = "󱨏" },
  { name = "*.aac", text = "󰈣" },
  { name = "*.odt", text = "󰈙" },
  { name = "*.ods", text = "󰱾" },
  { name = "*.odp", text = "󰈧" },
  { name = "*.odg", text = "󰈕" },
  { name = "*.odf", text = "󰠞" },
  { name = "*.docx", text = "󰈬" },
  { name = "*.ppt", text = "󰈧" },
  { name = "*.xlsx", text = "󰈛" },
  { name = "*.java", text = "󰬷" },
  { name = "*.js", text = "󰌞" },
  { name = "*.c", text = "󰙱" },
  { name = "*.cpp", text = "󰙲" },
  { name = "*.cs", text = "󰌛" },
  { name = "*.go", text = "󰟓" },
  { name = "*.hs", text = "󰲒" },
  { name = "*.lhs", text = "󰲒" },
  { name = "*.html", text = "󰌝" },
  { name = "*.kt", text = "󱈙" },
  { name = "*.lua", text = "󰢱" },
  { name = "*.md", text = "󰍔" },
  { name = "*.php", text = "󰌟" },
  { name = "*.py", text = "󰌠" },
  { name = "*.r", text = "󰟔" },
  { name = "*.ruby", text = "󰴭" },
  { name = "*.rc", text = "󱘗" },
  { name = "*.swift", text = "󰛥" },
  { name = "*.ts", text = "󰛦" },
  { name = "*.xml", text = "󰈮" },
  { name = "*.json", text = "󰈮" },
  { name = "*.yml", text = "󱁻" },
  { name = "*.yaml", text = "󱁻" },
  { name = "*.conf", text = "󱁻" },
  { name = "*.toml", text = "󱁻" },
  { name = "*.rasi", text = "󱁻" },
  { name = "*.ini", text = "󱁻" },
  { name = "*.stl", text = "󰐫" },
  { name = "*.3mf", text = "󰐫" },
  { name = "*.blend", text = "󰂫" },
  { name = "*.obj", text = "󰆦" },
  { name = "*.kmz", text = "󰆦" },
  { name = "*.fbx", text = "󰆦" },
  { name = "*.3ds", text = "󰆦" },
  { name = "*.cad", text = "󰻫" },
  { name = "*.pdf", text = "󱅷" },
  { name = "*.gpg", text = "󰈡" },
  { name = "*.gz", text = "󰛫" },
  { name = "*.zip", text = "󰛫" },
  { name = "*.7z", text = "󰛫" },
  { name = "*.tar", text = "󰀼" },
  { name = "*.deb", text = "󰀼" },
  { name = "*.rpm", text = "󰀼" }
]
