[colors.primary]
background = "#19171a"

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[window]
opacity = 0.8
